app/urls.py
from django.urls import path
from app import views

from app.feeds import LatestPostsFeed


app_name = 'app'


urlpatterns = [
    path('', views.home, name='home'),
    path('tag/<slug:tag_slug>/', views.home, name='post_list_by_tag'),
    path('tag/<slug:tag_slug>/', views.home, name='pinned_post_by_tag'),
    # path('', views.PostListView.as_view(), name='post_list'), 
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('add_post', views.add_post, name="add_post"),

    path('edit_post/<int:post_id>/', views.edit_post, name='edit_post'),
    path('delete_post/<int:post_id>/', views.delete_post, name='delete_post'),

    path('search', views.search, name="search"),
    # path('search_blog', views.search_blog, name="search_blog"),
    path('view_all_posts', views.view_all_posts, name='view_all_posts'),
    # path('<int:post_id>/comment/', views.post_comment, name="post_comment"),
    path('feed/', LatestPostsFeed(), name='post_feed'),



    path('template_test/', views.template_test, name='template_test'),
]

blog/urls.py
from django.contrib import admin
# from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# wrapping language
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.i18n import set_language

# adding sitemap
from django.contrib.sitemaps.views import sitemap
from app.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    # ck_editor 5 url
    path("ckeditor5/", include('django_ckeditor_5.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    # Sitempas url
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
)

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#

app/models.py
from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from django.urls import reverse
from django_ckeditor_5.fields import CKEditor5Field


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF', _('Draft')
        PUBLISHED = 'PB', _('Published')

    title = models.CharField(max_length=255, blank=True, null=True, verbose_name=_("Title"))
    slug = models.SlugField(max_length=250, blank=True, null=True, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    tags = TaggableManager(blank=True)
    authors_photo = models.ImageField(upload_to='media', blank=True, null=True)
    cover_photo = models.ImageField(upload_to='media', blank=True, null=True)
    # body = RichTextUploadingField(blank=True, null=True, verbose_name=_("Body"))
    body = CKEditor5Field(blank=True, null=True, config_name='extends')
    blockquote = models.TextField(max_length=200, blank=True, null=True, verbose_name=_("Blockquote"))
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateField(auto_now_add=True, blank=True, null=True)
    update = models.DateTimeField(auto_now=True, blank=True, null=True)
    pinned_post = models.BooleanField(default=False)
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT, verbose_name=_("Status"))

    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        verbose_name_plural = _("Posts")
        ordering = ['-publish']
        indexes = [models.Index(fields=['-publish'])]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("app:post_detail", args=[self.publish.year, self.publish.month, self.publish.day, self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80, verbose_name=_("Name"))
    email = models.EmailField(verbose_name=_("Email"))
    body = models.TextField(verbose_name=_("Body"))
    comment_photo = models.ImageField(upload_to='media', blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    update = models.DateTimeField(auto_now=True, blank=True, null=True)
    active = models.BooleanField(default=True, verbose_name=_("Active"))

    class Meta:
        ordering = ['created']
        indexes = [models.Index(fields=['created'])]

    def __str__(self):
        return f"Comment by {self.name} on {self.post}"


class Newsletter(models.Model):
    email = models.EmailField(unique=True, verbose_name=_("Email"))

    def __str__(self):
        return f'{self.email} subscribed to your newsletter'

    def clean(self):
        try:
            validate_email(self.email)
        except ValidationError as e:
            raise ValidationError({'Email': _("Invalid email format")})

app/forms.py
from django import forms
from taggit.forms import TagWidget
from .models import *


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body', 'comment_photo']


class PostForm(forms.ModelForm):
    tags = forms.CharField(widget=TagWidget(), required=False)
    class Meta:
        model = Post
        fields = ['title', 'slug', 'author', 'tags', 'authors_photo', 'cover_photo', 'body', 'blockquote', 'status', 'pinned_post', 'publish']


class NewsletterForm(forms.ModelForm):
    class Meta:
        model = Newsletter
        fields = ['email']

# class SearchForm(forms.Form):
#     search_title = forms.CharField(label='Seach by title', max_length=100)

templates/app/all_posts.html
{% extends 'app/elements/admin.html' %}
{% load static %}
{% load blog_tags %}

{% load i18n %}

{% get_current_language as LANGUAGE_CODE %}
{% get_available_languages as LANGUAGES %}
{% get_language_info_list for LANGUAGES as languages %}


{% block content %}
<main>
    <div>
      <h2 class="fw-bold container mt-4">All Posts</h2>
    </div>
    <section class="py-4 my-4">
        <div class="container card__">
            <div class="row">
              {% for post in posts %}
                <div class="col-xl-4 col-md-12 col-sm-12 mb-4">
                    <div class="card shadow-md">
                      <img src="{{post.cover_photo.url}}" class="card-img-top" alt="...">
                      <div class="card-body">
                        <h5 class="card-title fs-3 fw-bold">{{ post.title|slice:":24"|safe }}</h5>
                        <p class="card-text">{{ post.body|slice:":70"|safe }}...</p>
                        <a href="{{ post.get_absolute_url }}" class="btn blog__button">Read more...</a>
                      </div>
                    </div>
                </div>

                {% endfor %}
            </div>


        </div>
    </section>



    <section class="scroll__to__top shadow-lg" id="scrollToTop">
        <div>
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-chevron-up" viewBox="0 0 16 16">
              <path fill-rule="evenodd" d="M7.646 4.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1-.708.708L8 5.707l-5.646 5.647a.5.5 0 0 1-.708-.708l6-6z"/>
            </svg>
        </div>
    </section>

</main>
{% endblock %}

templates/app/delete_confirmation.html
{% extends "app/base.html" %}

{% load blog_tags %}
{% load static %}

{% block content %}

<!-- delete_confirmation.html -->
<main class="container">


<section class="comment-section">
    <div class="comment-form">

        <div class="parent-comment-div" style="display:flex; flex-direction:column;">
            <h2>Delete Confirmation</h2>
                <p>Are you sure you want to delete "{{ post.title }}"?</p>

                <form action="{% url 'app:delete_post' post_id=post.id %}" method="post" >
                    {% csrf_token %}

                    <button type="submit">Yes, Delete Post!</button>
                </form> 


                <a href="{% url 'app:home' %}">Cancel</a>
        </div>
    </div>
</section>


</main>
{% endblock content %}

templates/app/detail.html
{% extends 'app/elements/admin.html' %}
{% load static %}
{% load blog_tags %}
{% load i18n %}

{% block content %}
<main class="container main__">
    <div class="text-center">{% include "app/elements/messages.html" %}</div>
    <section class="row">
        <h2 class="fw-bold mt-2 pb-4">{% trans 'Post Details' %} </h2>
        <div class="col-xl-4">
            <div>
                <p>{% trans 'A' %} {{ reading_time }} {% trans 'minute(s) read' %}.</p>
                <div class="author__">
                    <div class="authors__img">
                        <img src="{{posts.authors_photo.url}}" alt="authors__img">
                    </div>
                    <div class="authors__name">
                        <h5 class="mb-0 pt-3">{{ posts.author }}</h5>
                        <p class="mt-0 pt-0">{{ posts.publish }}</p>
                    </div>
                </div>

            </div>

            <div class="tag-slug p-3">
<!--                <div class="tag__">-->
<!--                    <span class="fw-bold text-light">Tag:</span> <a href="" class="btn btn-sm btn-outline-light ">{{ posts.tag }}</a>-->
<!--                </div>-->
                <div class="slug__ pt-2">
                    <span class="fw-bold text-light">Slug: </span><a href="" class="btn btn-sm btn-outline-light ">{{ posts.slug }}</a>
                </div>
                {% if user.is_authenticated %}

                <div class="edit-post d-flex gap-2 pt-4">
                  <a href="{% url 'app:edit_post' post_id=posts.id %}" class="btn btn-md bg-primary text-light fw-bold">Edit Post</a>
                  <a href="#-{{posts.pk}}" data-bs-toggle="modal" data-bs-target="#exampleModal-{{posts.pk}}" class="btn btn-md bg-danger fw-bold text-light">Delete Post</a>
                </div>

                {% else %} {% endif %}
            </div>

            <h4 class="my-3 mt-5">{% trans "Related Posts" %}</h4>
            {% if similar_posts %}
            {% for post in similar_posts %}
            <div class="related__posts">
                <div class="related__posts_img">
                    <img src="{{post.cover_photo.url}}" alt="related__posts">
                </div>
                <div class="related__posts_title">
                    <h4>
                        <a href="{{ post.get_absolute_url }}" class="text-dark">{{ post.title|slice:":24"|safe }}</a>
                    </h4>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <p>No related post</p>
            {% endif %}


        </div>
        <div class="col-xl-8">
            <div class="card detail__card" style="">
              <img src="{{posts.cover_photo.url}}" class="card-img-top" alt="...">
              <div class="card-body">
                  <h2 class="card-title pb-3 fw-bold">{{ posts.title }}</h2>
                <p class="card-text">{{ posts.body|safe }}</p>
              </div>
            </div>

            <div class="card shadow-md comment__">
<!--                <h4 class="pb-2 fw-bold">Leave a comment</h4>-->
                <form>
                    <div class="row">
                        <div class="col-xl-6 col-md-6 col-sm-6">
                            <div class="mb-3">
                              <label for="exampleFormControlInput1" class="form-label">email</label>
                              <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="email@email.com">
                            </div>
                        </div>
                        <div class="col-xl-6 col-md-6 col-sm-6">
                            <div class="mb-3">
                              <label for="exampleFormControlInput1" class="form-label">name</label>
                              <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="name...">
                            </div>
                        </div>
                    </div>
                    <div class="mb-3">
                      <label for="exampleFormControlTextarea1" class="form-label">comment</label>
                      <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
                    </div>

                    <div class="submit__">
                        <button class="btn btn-md text-light fw-bold" type="submit">Add comment</button>
                    </div>
                </form>
            </div>
        </div>


    </section>


    <section class="scroll__to__top shadow-lg" id="scrollToTop">
        <div>
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-chevron-up" viewBox="0 0 16 16">
              <path fill-rule="evenodd" d="M7.646 4.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1-.708.708L8 5.707l-5.646 5.647a.5.5 0 0 1-.708-.708l6-6z"/>
            </svg>
        </div>
    </section>



    <!-- Modal -->
    <div class="modal fade" id="exampleModal-{{posts.pk}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content modal-content__">
          <div class="modal-header">
            <h1 class="modal-title fs-5 fw-bold" id="exampleModalLabel">{{ posts.title|slice:":35"|safe }}</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
              <p>{% trans 'You are about to delete this post' %} <span class="fw-bold">{{ posts.title|safe }}</span>. {% trans 'This action is permanent and cannot be undone. Are you sure you want to proceed?' %}</p>
          </div>
          <div class="modal-footer">
              <form method="post" action="{% url 'app:delete_post' post_id=posts.id %}">
                  {% csrf_token %}
                  <button type="submit" class="btn modal-content-btn__">Delete</button>
              </form>
          </div>
        </div>
      </div>
    </div>

</main>
{% endblock %}

templates/app/edit_post.html
{% extends 'app/elements/admin.html' %}
{% load static %}
{% load blog_tags %}
{% load i18n %}


{% block content %}

<!-- edit_post.html -->

<main class="container my-5">
  <div class="mb-5">
    <a href="{{ posts.get_absolute_url }}" class="bg-dark text-light p-2 rounded-2">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"/>
      </svg>
      Back </a>
  </div>

<form method="post" enctype="multipart/form-data" action="{% url 'app:edit_post' post_id=posts.id %}" class="add-post-form__">
    {% csrf_token %}
    <div class="card shadow-md">
        <div class="row">
            <div class="col-xl-6 col-md-12">
                <!-- Title Field -->
                <div class="mb-3">
                    <label for="id_title" class="form-label">Title</label>
                    <input type="text" class="form-control" id="id_title" name="title" value="{{ form.title.value|default:'' }}">
                </div>
            </div>
            <div class="col-xl-6 col-md-12">
                <!-- Slug Field -->
                <div class="mb-3">
                    <label for="id_slug" class="form-label">Slug</label>
                    <input type="text" class="form-control" id="id_slug" name="slug" value="{{ form.slug.value|default:'' }}">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xl-6 col-md-12">
                <!-- Author Field -->
                <div class="mb-3">
                    <label for="id_author" class="form-label">Author</label>
                    <select class="form-select" id="id_author" name="author">
                        {% for author in form.author.field.queryset %}
                            <option value="{{ author.id }}" {% if author.id == form.author.value %}selected{% endif %}>
                                {{ author.username }}
                            </option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="col-xl-6 col-md-12">
                <!-- Status Field -->
                <div class="mb-3">
                    <label for="id_status" class="form-label">Status</label>
                    <select class="form-select" id="id_status" name="status">
                        <option value="DF" {% if form.status.value == 'DF' %}selected{% endif %}>Draft</option>
                        <option value="PB" {% if form.status.value == 'PB' %}selected{% endif %}>Published</option>
                    </select>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xl-6 col-md-12">
                <!-- Authors Photo Field -->
                <div class="mb-3">
                    <label for="id_authors_photo" class="form-label">Authors Photo</label>
                    {% if posts.authors_photo %}
                        <img src="{{ posts.authors_photo.url }}" alt="Authors Photo" style="max-width: 100px; max-height: 100px;">
                    {% endif %}
                    <input type="file" class="form-control" id="id_authors_photo" name="authors_photo" accept=".png, .jpg, .jpeg">
                </div>

            </div>
            <div class="col-xl-6 col-md-12">
                <!-- Cover Photo Field -->
                <div class="mb-3">
                    <label for="id_cover_photo" class="form-label">Cover Photo</label>
                    {% if posts.cover_photo %}
                        <img src="{{ posts.cover_photo.url }}" alt="Cover Photo" style="max-width: 100px; max-height: 100px;">
                    {% endif %}
                    <input type="file" class="form-control" id="id_cover_photo" name="cover_photo" accept=".png, .jpg, .jpeg">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xl-12 col-md-12">
                <!-- Body Field (Rich Text) -->
                <div class="mb-3">
                    <label for="postBody" class="form-label">Content</label>
                    <textarea class="form-control" id="postBody" name="body">{{ form.body.value|default:'' }}</textarea>
                </div>

                <script>
                    ClassicEditor
                        .create(document.querySelector('#postBody'))
                        .catch(error => {
                            console.error(error);
                        });
                </script>
            </div>
        </div>
        <div class="row">
            <div class="col-xl-6 col-md-12">
                <!-- Tags Field -->
                <div class="mb-3">
                    <label for="id_tags" class="form-label">Tags</label>
                    <input type="text" class="form-control" id="id_tags" name="tags" value="{{ form.tags.value|default:'' }}">
                </div>
            </div>
            <div class="col-xl-6 col-md-12">
                <!-- Blockquote Field -->
                <div class="mb-3">
                    <label for="id_blockquote" class="form-label">Blockquote</label>
                    <input type="text" class="form-control" id="id_blockquote" name="blockquote" value="{{ form.blockquote.value|default:'' }}">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xl-6 col-md-12">
                <!-- Publish Date Field -->
                <div class="mb-3">
                    <label for="id_publish" class="form-label">Publish Date</label>
                    <input type="datetime-local" class="form-control" id="id_publish" name="publish" value="{{ form.publish.value|default:'' }}">
                </div>
            </div>
            <div class="col-xl-6 col-md-12">
                <!-- Pinned Post Field -->
                <div class="mb-3 form-check">
                    <input type="checkbox" class="form-check-input" id="id_pinned_post" name="pinned_post" {% if form.pinned_post.value %}checked{% endif %}>
                    <label class="form-check-label pt-2 ms-2" for="id_pinned_post">Pinned Post</label>
                </div>
            </div>

        </div>


        <!-- Submit Button -->
        <button type="submit" class="btn publish__btn my-3">Save Changes</button>
    </div>
</form>

  
</main>

{% endblock content %}

templates/app/index.html
{% extends 'app/elements/admin.html' %}
{% load static %}
{% load blog_tags %}
{% load i18n %}


{% block content %}
<main>

    <section class="banner mb-3">
        <div class="text-center">{% include "app/elements/messages.html" %}</div>
        <div class="image__section">
            <div class="image__">
            </div>
            <div class="text__section">
                <h1 class="pt-3">{% trans "Your online Grocery Store!" %}</h1>
                <p>{% trans "where we manage your inventory for you..." %}</p>
                <div class="text__section_link">
                <a href="{% url 'app:view_all_posts' %}" class="btn text-light shadow-lg">{% trans "Explore Blog" %}</a>
                </div>

            </div>
        </div>
    </section>

    <section class="search container my-4">
        <form class="d-flex" role="search" method="post" action="{% url 'app:search' %}">
            {% csrf_token %}
            <input class="form-control me-2 py-2 px-3" type="search" name="search_term" placeholder="search here..." aria-label="Search">
            <button class="btn btn-outline-success px-3" type="submit">Search</button>
        </form>
    </section>

    {% if request.user.is_authenticated %}
    <section class="container add-post">
        <a href="{% url 'app:add_post' %}" class="btn">Add post</a>
    </section>
    {% else %}
    {% endif %}

    <section class="py-4">
        <div class="container card__">
            <div class="row">
              {% for post in posts %}
                <div class="col-xl-4 col-md-12 col-sm-12 mb-4">
                    <div class="card shadow-md">
                      <img src="{{post.cover_photo.url}}" class="card-img-top" alt="...">
                      <div class="card-body">
                        <h5 class="card-title fs-3 fw-bold">{{ post.title|slice:":24"|safe }}</h5>
                        <p class="card-text">{{ post.body|slice:":70"|safe }}...</p>
                        <a href="{{ post.get_absolute_url }}" class="btn blog__button">Read more...</a>
                      </div>
                    </div>
                </div>

                {% endfor %}
            </div>


        </div>
    </section>



    <div class="paginator">
        {% include "app/paginator.html" with page=posts %}
    </div>

    <section class="scroll__to__top shadow-lg" id="scrollToTop">
        <div>
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-chevron-up" viewBox="0 0 16 16">
              <path fill-rule="evenodd" d="M7.646 4.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1-.708.708L8 5.707l-5.646 5.647a.5.5 0 0 1-.708-.708l6-6z"/>
            </svg>
        </div>
    </section>

</main>
{% endblock %}

templates/app/latest_posts.html
{% load blog_tags %}
{% load static %}



{% block content %}

<!-- First column -->
<div class="posts">
    {% for post in latest_posts %}
    <div class="first-post">
      <div class="first-post-image"
      style="background-image:url('{{post.cover_photo.url}}')"
      ></div>
      <div class="badge">
        <button>{{post.slug}}</button>
      </div>
      <div class="first-post-title">
        <a href="{{ post.get_absolute_url }}">
          <h2>{{ post.title|truncatewords:3 }}</h2>
        </a>
      </div>
      <div class="first-post-author">
        <div class="first-post-author-image"
        style="background-image:url('{{post.authors_photo.url}}')"
        ></div>
        <div class="first-post-authors-name">
          <span> {{ post.publish }}</span> |
          <span> {{ post.author }}</span>
        </div>
        
        <div class="first-post-date-published">
        </div>
      </div>
      {% comment %} <small>Tags: {{ post.tags.all|join:", " }}</small> {% endcomment %}
      <div class="tags">
        <small>Tags:
          {% for tag in post.tags.all %}
          <a href="{% url "app:post_list_by_tag" tag.slug %}">
            {{tag.name}}
          </a>
          {% if not forloop.last %}, {% endif %}
          {% endfor %}
        </small>
      </div>

    </div>
    {% endfor %}
     
  </div>

{% endblock content %}

templates/app/share.html
{% extends "app/base.html" %}

{% load blog_tags %}
{% load static %}
{% block content %}



<main class="container">

    <section class="banner">
      {% for latest in latest_post %}

      <div class="banner-image"
      style="background-image:url('{{latest.cover_photo.url}}')"
      >
      </div>

      <div class="jumbotron">
        <div class="badge">
          <button>{{latest.slug}}</button>
        </div>
        <div class="banner-title">
          <a href="{{latest.get_absolute_url }}">
            <h1>
              {{latest.title}}
            </h1>
          </a>
        </div>
        <div class="banner-author">
          <div class="author-image"
          style="background-image:url('{{latest.authors_photo.url}}')"
          ></div>
          <div class="authors-name">
            <p>By: {{latest.author}}</p>
          </div>
          <div class="date-published">
            <p>{{latest.publish}}</p>
          </div>
        </div>


        {% endfor %}
      </div>
    </section>

    <div class="view-all-post-button" style="display:flex; justify-content:end;">
    <form action="{% url 'app:add_post' %}">
      <button>Add Post</button>
    </form>
    </div>

    <section class="main-text">
      <h2>Blog Posts</h2>
      {% if tag %}
      <h2>Posts tagged with "{{ tag.name }}"</h2>
      {% endif %}
      <!-- First column -->
      <div class="posts" id="post-list">
        {% for post in posts %}
        <div class="first-post">
          <div class="first-post-image"
          style="background-image:url('{{post.cover_photo.url}}')"
          ></div>
          <div class="badge">
            <button>{{post.slug}}</button>
          </div>
          <div class="first-post-title">
            <a href="{{ post.get_absolute_url }}">
              <h2>{{ post.title|truncatewords:3 }}</h2>
              {% comment %} <h2>{{ post.body|markdown|truncatewords_html:30 }}</h2> {% endcomment %}
            </a>
          </div>
          <div class="first-post-author">
            <div class="first-post-author-image"
            style="background-image:url('{{post.authors_photo.url}}')"
            ></div>
            <div class="first-post-authors-name">
              <span> {{ post.publish }}</span> |
              <span> {{ post.author }}</span>
            </div>

            <div class="first-post-date-published">
            </div>
          </div>
          {% comment %} <small>Tags: {{ post.tags.all|join:", " }}</small> {% endcomment %}
          <div class="tags">
            <small>Tags:
              {% for tag in post.tags.all %}
              <a href="{% url "app:post_list_by_tag" tag.slug %}">
                {{tag.name}}
              </a>
              {% if not forloop.last %}, {% endif %}
              {% endfor %}
            </small>
          </div>

        </div>
        {% endfor %}

      </div>



      <div class="paginator">
        {% include "app/paginator.html" with page=posts %}
      </div>

      <div class="view-all-post-button">


        <form action="{% url 'app:view_all_posts' %}">
          <button>View All Post</button>
        </form>

      </div>

      <h3>Latest posts</h3>
      {% show_latest_posts 1 %}

      <div class="newsletter">
        <form action="" method="post">
          {% csrf_token %}
          <fieldset>
            <legend>Subscribe to newsletter</legend>
            <div>
              <input type="email" name="email" placeholder="Your email...">
            </div>
            <div>
              <button type="submit">Subscribe</button>
            </div>

          </fieldset>
        </form>
      </div>

      <br>

      {% comment %} <h3>Most commented posts</h3>
      {% get_most_commented_posts as most_commented_posts %}
      {% if most_commented_posts %}
      <ol>
        {% for post in most_commented_posts %}
        <li>
          <a href="{{ post.get_absolute_url }}">{{ post.title|upper }}</a>
        </li>
        {% endfor %}
      </ol>
      {% else %}

      {% endif %} {% endcomment %}


      <br>

      {% comment %} <p>
        <a href="{% url "app:post_feed" %}">
        Subscribe to my RSS feed
        </a>
        </p>
      <br> {% endcomment %}
      <div> <b> {% total_posts %} </b> posts published so far.</div>

    </section>
  </main>






{% endblock content %}